test_that("correlation plot guards insufficient data without validate errors", {
  server_file <- test_path("..", "..", "inst", "app", "server", "server_main.R")
  corr_file <- test_path("..", "..", "inst", "app", "graficos", "graficos_correlacion.R")
  expect_true(file.exists(server_file))
  expect_true(file.exists(corr_file))

  txt_server <- paste(readLines(server_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  txt_corr <- paste(readLines(corr_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_true(grepl('if \\(tipo == "Correlacion"\\)', txt_server, perl = TRUE))
  expect_true(grepl("build_correlation_plot_impl\\(", txt_server, perl = TRUE))
  expect_true(grepl("corr_placeholder <- function\\(msg\\)", txt_corr, perl = TRUE))
  expect_true(grepl("if \\(nrow\\(df\\) < 3\\) \\{", txt_corr, perl = TRUE))
  expect_true(grepl("corr_no_overlap_points", txt_corr, fixed = TRUE))
  expect_true(grepl("corr_not_enough_overlap_points", txt_corr, fixed = TRUE))
  expect_true(grepl("return\\(corr_placeholder\\(", txt_corr, perl = TRUE))
  expect_false(grepl("validate\\(need\\(\\s*nrow\\(df\\) >= 3", txt_corr, perl = TRUE))
})

test_that("plot_base suppresses noisy notifications for transient expected states", {
  server_file <- test_path("..", "..", "inst", "app", "server", "server_main.R")
  txt <- paste(readLines(server_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_true(grepl('inherits\\(e, "shiny\\.silent\\.error"\\)', txt, perl = TRUE))
  expect_true(grepl("is_expected_transient", txt, fixed = TRUE))
  expect_true(grepl("if \\(!is_expected_transient\\)", txt, perl = TRUE))
})

test_that("advanced correlation is button-driven and stats table guards empty params", {
  server_file <- test_path("..", "..", "inst", "app", "server", "server_main.R")
  corr_file <- test_path("..", "..", "inst", "app", "graficos", "graficos_correlacion.R")
  txt_server <- paste(readLines(server_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  txt_corr <- paste(readLines(corr_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  expect_true(
    grepl("corr_adv_results <- eventReactive\\(input\\$corr_adv_run,", txt_server, perl = TRUE) ||
      grepl("corr_adv_results <- reactiveVal\\(", txt_server, perl = TRUE)
  )
  expect_true(grepl("observeEvent\\(input\\$corr_adv_run,", txt_server, perl = TRUE))
  expect_true(grepl("corr_adv_press_run", txt_server, fixed = TRUE))
  expect_true(grepl("corr_adv_last_pair <- reactiveVal\\(NULL\\)", txt_server, perl = TRUE))
  expect_true(grepl("corr_adv_last_pair\\(list\\(x = anchor, y = other\\)\\)", txt_server, perl = TRUE))
  expect_true(grepl("output\\$corr_adv_summary <- renderUI\\(", txt_server, perl = TRUE))
  expect_true(grepl("output\\$download_corr_adv <- downloadHandler\\(", txt_server, perl = TRUE))
  expect_true(grepl("corr_df <- as\\.data\\.frame\\([\\s\\S]*check\\.names\\s*=\\s*FALSE", txt_server, perl = TRUE))
  expect_true(grepl("has_finite_col <- function\\(df, col_name\\)", txt_server, perl = TRUE))
  expect_true(grepl("params_ready <- params_ready\\[vapply\\(", txt_server, perl = TRUE))
  expect_true(grepl("pair_ready <- others\\[vapply\\(others, function\\(other\\)", txt_server, perl = TRUE))
  expect_true(grepl("output\\$corrAdvDownloadReady <- renderText\\(", txt_server, perl = TRUE))
  expect_true(grepl("openxlsx::addWorksheet\\(wb, \"correlaciones\"\\)", txt_server, perl = TRUE))
  expect_true(grepl("correlacion = r", txt_server, fixed = TRUE))
  expect_true(grepl("p_value = p.value", txt_server, fixed = TRUE))
  expect_true(grepl("!nzchar\\(raw_x\\) \\|\\| !nzchar\\(raw_y\\)", txt_server, perl = TRUE))
  expect_true(grepl("all\\(c\\(col_x, col_y\\) %in% names\\(df\\)\\)", txt_server, perl = TRUE))
  expect_true(grepl("stat_pair <- correlation_pair_with_p\\(", txt_corr, perl = TRUE))
  expect_true(grepl("df_stats <- df %>%", txt_corr, perl = TRUE))
  expect_true(grepl("fit <- tryCatch\\(stats::lm\\(Y ~ X, data = df_stats\\)", txt_corr, perl = TRUE))
  expect_true(grepl("manual_x_limits <- is.finite\\(xmin_in\\) && is.finite\\(xmax_in\\) && xmax_in > xmin_in", txt_corr, perl = TRUE))
  expect_true(grepl("manual_y_limits <- is.finite\\(ymin_in\\) && is.finite\\(ymax_in\\) && ymax_in > ymin_in", txt_corr, perl = TRUE))
  expect_true(grepl("if \\(manual_x_limits\\)", txt_corr, perl = TRUE))
  expect_true(grepl("if \\(manual_y_limits\\)", txt_corr, perl = TRUE))
  expect_true(grepl("min_out <- if \\(lo_raw >= 0\\) 0 else snap_down_1\\(lo_raw - pad\\)", txt_server, perl = TRUE))
  expect_true(grepl("step <- round(step, 1)", txt_server, fixed = TRUE))
})
