name: R tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NOT_CRAN: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up R
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590
        with:
          extra-packages: |
            any::testthat
            any::shinytest2
            any::chromote
          needs: check

      - name: Run testthat suite
        run: Rscript -e "testthat::test_dir('tests/testthat')"
